### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by xKiraiChan** [ImStellar/Client-Detector#4]
https://github.com/ImStellar/Client-Detector/blob/master/Client%20Detector/ClientSeek.cs

This file does not display correctly within the GitHub file viewer.

I'm trying to figure out how this happened, my theories are:
* This is your coding style
* The code was written in an editor like `notepad.exe` which shows tabs as 8 chars long while other editors show it as 4 chars long
* The code was copy and pasted and then mangled by Visual Studio's auto formatter

If you could clarify that would be great.

**Comment by ImStellar** [comment]
I don't know either it's not broken in visual studio I noticed that before you did but I just did not care enough to rectify it.

**Comment by Love3000** [comment]
its cause he pasted the code from my client decompiled lol.

**Comment by ImStellar** [comment]
Love claimed that the queue players code was his when it's in fact not, look at him trying to take credit for everything what a stupid child LMAO

**Comment by xKiraiChan** [comment]
Considering you delete issues and comments I would say that you are more childish than @Love3000. Other people should be able to express themselves without censorship.
After all, censorship proves that your claims are not strong enough to stand up on their own and need to be protected

You close every issue without any proper fix or explanation. Instead of fixing this issue you just said you didn't care and then closed. Why do you not care? Is the repository archived? It's not.

Please, grow up and show some professionalism on a formal website like GitHub.

@abbe might be able to elaborate a bit more on my comment here.

**Comment by ImStellar** [comment]
Um I gave him ample time to respond I even responded as well but then he went hushmode so if there is no actual issue then why not delete them? I also deleted them because they are lies and trolling I don't want that platform on my github Love complained about something I already rectified I did *credit* the extensions and what not but I will not go any further on this kid because I don't like him. I don't care because the code formatting is a small issue, like you guys are all being pedantic af nobody needs to fix some of this stuff there is nothing wrong with this mod everything works right. All the features I enumerated work. And I don't think you want to talk professionalism with me when you come on my github nitpicking every little thing and even brought abbez in here to troll with, when i was in call with abbez he literally said he was going to spam i like turtles on my github like what?

**Comment by ImStellar** [comment]
He was just going to leave those fake issues on my repo and then dip when I respond to them so if he's not going to have an actual debate with me then I will cease the repository, BTW I regret deleting it a little bit because I actually refuted everything he said so it would of been more beneficial for me to keep it up anyways but I didn't want toxicity on my github so.

**Comment by ImStellar** [comment]
Also kirai chan let's take you for example in terms of lack of professionalism I mean after-all you ratted all of your users when you got banned on discord as a sort of temper tantrum, your users did not deserve that. Also you interloped into someone elses discussion you knew nothing about and instantly started attacking ME when we first met, you saw me trying to quiz inu and that made you angry because you know inu is not a coder so you lashed out on me! BUT! Little did you know Inu was actually the first person to start the quizzing when I called him out on his name he asked me what a DWORD was so I think it's only fair that I quiz him back no?

**Comment by ImStellar** [comment]
And then I also called you out on your skidding of love's rpc sender which also made you mad so you've made it your goal to try and smear me as much as possible because YOU are the one who wants to hide the truth from the public, that's why you stalk my twitter and github.

**Comment by ImStellar** [comment]
I figure you don't like toxicity as well Kirai Chan something me and you I'm sure can find common ground on as the last time we argued you were quick to ban me from the discord server we were arguing in and then every time we argue there is always a stoppage midway. I mean we argued on twitter last time remember and guess what after I said everything I said you stopped responding care to explain that? I feel like you honestly were just misinformed and it's okay I understand you fell for a misconception you didn't know that inu was the one who quizzed me first and so on I get that. It's not too late to stop this conflict as it was unnecessary to begin with...

**Comment by ImStellar** [comment]
You obviously left the modding community for a reason I don't think I'm worth it for you keep fighting against, every time you respond to me is every time you spend back in the modding community so...

**Comment by ImStellar** [comment]
I don't care about who is a script kiddie and who isn't a script kiddie I'm beyond that, because in truth we all are. Skid is such an empty insult at this point all that matters if the result of everything you make. Not about how it was done. We could sit here all day going back and forth on who is the better coder than who but that accomplishes nothing. Maybe if you were not immature Kirai and Abbez you would understand that.

**Comment by xKiraiChan** [comment]
> if there is no actual issue then why not delete them?

For future people making issues to know that its already been resolved.
> I also deleted them because they are lies and trolling I don't want that platform on my github

False.

> And I don't think you want to talk professionalism with me when you come on my github nitpicking every little thing

Professionally*. High quality code is easier to maintain. I have no clue how I'm meant to understand this repo when the entire thing has broken formatting.

> All the features I enumerated work

"enumerated" makes no sense in this context.

> he literally said he was going to spam i like turtles on my github like what?

Frog said it once, I fail to see how that is spamming

> I mean after-all you ratted all of your users

RAT means Remote Access Trojan. There was no trojan, and there was no remote access. Creating empty files is harmless.
Please, educate yourself.

> your users did not deserve that

I made it very clear that anyone not in the server was not allowed to run my mod. Nobody was in the server so nobody was allowed in the mod. There was a check so it would only fire if KiraiMod was loaded, not Cartridge, not KiraiLog, not KiraiComms, not any mod but that one.

> Also you interloped into someone elses discussion you knew nothing about

When?

> instantly started attacking ME when we first met

10 minutes is not instantly. You attacked someone for something they never said.
You always act like you are the victim.

> Little did you know Inu was actually the first person to start the quizzing when I called him out on his name he asked me what a DWORD was so I think it's only fair that I quiz him back no?

This is logically false because who would ever ask someone the exact same question that they just got asked? They clearly know the answer or they wouldn't ask in the first place.

> And then I also called you out on your skidding of love's rpc sender which also made you mad so you've made it your goal to try and smear me as much as possible

@Love3000, do you affirm that you started the myth to try to seem cool to Zephoriah?
After all, I did show that I had the code **before** Love ever showed it to me.
Lets remember the original point of the conversation. Love didn't know how to target Udon and had to ask me about `UdonBehaviour.SendCustomNetworkEvent`

> YOU are the one who wants to hide the truth from the public

I've always made everything I do public. I don't obfuscate for a reason. If I wanted to hide then I could run ConfuserEx like you.

> that's why you stalk my twitter and github.

SVH members send me whenever you do something. I don't go out of my way to watch your mistakes.

> You obviously left the modding community for a reason

I never left.

> Maybe if you were not immature Kirai and Abbez you would understand that.

You delete posts because we say you took code, you ban me from your server after begging for ownership from Sypherr because I disagree with you.

> I don't care about who is a script kiddie and who isn't a script kiddie I'm beyond that, because in truth we all are.

False generalities are a great way at making it seem like what you are doing is alright. 
It has been proven that this is false. People like @knah, @requi-dev, or Teo have proven that they know what they are doing.
I understand that you are new to the hacking scene but some of us like Requi and I have an extensive history on uC and native level hacking without a modding framework.
Also you wrote 7 comments, spamming my email in the process, thank you.

**Comment by ImStellar** [comment]
1. Yeah but kirai chan they are not actual issues the only thing remotely close to an issue was yours and that was on the basis of formatting which is a harmless problem you can fix yourself if *you are so much better at coding*

2. Yes kirai chan they are lies Love took credit for my fucking queue players which was made by ME not HIM. That's just a blatant lie. 

3. Last I checked the only thing broken in terms of formatting was the queue players? And this really shouldn't even be a problem for even a beginner.

4. Um no professionalism was the right word to use, you are talking "professionalism" with me, I did not mean to say you are talking professionally with me that would be wrong to the point I was trying to convey was that you are trying to talk the topic that is known as professionalism with me. See kirai chan maybe you shouldn't be such a pedantic sometimes it can backfire as you just showed your fail comprehension skills to everyone now : )

5. Enumerate - mention (a number of things) one by one.
I am referring to the features I enumerated which basically means the features I mentioned one by one. See another failed correction LMAO is this how you argue kirai chan? Trying to attack little things?

6. I was not referring to just frog, Abbez said he would...

7. So you *did* rat your users hahahahah so you just admitted you intentionally installed bloatware on your psuedo users pcs? that's messed up some people just wanted a nice client to use they didn't deserve to get ratted either way. And when I use the term ratted I'm referring to any unauthorized actions done to ones computer maliciously I don't care about the exact definition.

8. you interloped on my conversation between me and inu.

9. No the moment you joined and saw me quiz inu and you started going at me without a second thought without ever wondering why I was quizzing him? I don't care to play victim I'm just playing the defensive because all you guys do is low blows towards me so sometimes I do have to make it very clear that you are the guys instigating this and escalating these conflicts.

10. He asked me first what a DWORD was? LOL WDYM this is logically false? I mean if he asked me that first then later on i probably asked him as well as a way to test if he actually knew what he was talking about? that makes perfect sense I think you are not seeing the bigger picture here...

11. You have yet to prove it I see no date and time of when you posted that commit except for 2 months ago which we met way longer before that btw.

12. I'm not referring just referring to code I am also referring to your reputation as well, but yes you are constantly trying to hide that you skidded. And just because you keep it overt doesn't mean everyone will know it's from love because if you think about it love never makes anything public except for small things and that was not small.

13. Github isn't meant for drama so I have the right to remove your bs posts the only thing you are calling out is the fact I used his extensions which does not matter in anyway I openly credited him on it, and I banned you because you were going to ping the whole server a billion times with something I could not repond to (because I was going to sleep) so i protensively removed you.

14. Oh so you are cherrypicking Knah, and people like Requi? Those are representative of the majority of the modders I agree they have actual talent. But I'm sure even they have gotten somethings from stackoverflow and things like that, I know that could be entirely false but I don't care I'm 90% sure it's true.

**Comment by ImStellar** [comment]
And I see so you never actually quitted the modding community you just quit making your client?

**Comment by ImStellar** [comment]
BTW Kirai I will give you the benefit of the doubt on your point against love trying to act cool towards me, as someone who was friends with him for a long time I can say confidently this guy likes to flex many things to his friends. So yes it' not farfetched to say he made that up, but i've seen the before and after. And the explanation everything makes sense in that regard. Now it's up to you to refute that...

**Comment by xKiraiChan** [comment]
> Yes kirai chan they are lies Love took credit for my fucking queue players which was made by ME not HIM. That's just a blatant lie.

Decide. Is everything love says a lie or is it all truthful?
Either you took his queue players and I took his RPC **--or--** neither of us took code.

> Oh so you are cherrypicking Knah, and people like Requi? Those are not representative of the majority of the modders I agree they have actual talent. But I'm sure even they have gotten somethings from stackoverflow and things like that, I know that could be entirely false but I don't care I'm 90% sure it's true.

You said "everyone". Of course I would pick a few examples.

> Github isn't meant for drama

Self contradiction.

> And just because you keep it overt

Overt = Obvious
Covert = Hidden

> So you did rat your users hahahahah so you just admitted you intentionally installed bloatware on your psuedo users pcs?

14 empty files take around 4 kilobytes due to NTFS. Bloatware is typically software that takes up RAM or CPU time.

> I can say confidently this guy likes to flex many things to his friends.

Projection.

> And the explanation everything makes sense in that regard

Confirmation Bias.

> Now it's up to you to refute that...

I did. Many times. You are ignoring it.

**Comment by ImStellar** [comment]
Okay now so what you are doing is like bottom level 4 of the refutation pyramid you are not even trying to make a counter argument, just lousily making 1 sentence opposing cases
![origin](https://user-images.githubusercontent.com/82069239/124219644-7449eb00-dab1-11eb-8719-eef13675be83.jpg)

**Comment by xKiraiChan** [comment]
I want to write code but instead I'm constantly getting emailed. Of course I would write the quickest response I can.
Also technically I've been on level 6, calm down.

**Comment by ImStellar** [comment]
1. That's a false dilemma I don't have to agree with this in order for both instances to be true, I'm not saying love lies about everything I'm saying lately he's lied about a lot towards me. Of course there are instances were love is not lying.
2. I didn't contradict myself just because i'm responding to your claims doesn't mean I'm spreading drama on github?
3. Yes KIRAI CHAN! You are keeping your code overt so everyone can see you are not "skidding" but nobody would know if you skidded or not because they would need the comparative to go off of which would be love's code and love does not share his code often so even if you kept it open no one would know.
4. Why would you do that in the first place if it's not "malicious enough" ? I mean what were you just trying to scare them so they will stop using your client? 
5. How am I projecting myself onto love? when do i ever flex stuff to my friends except characters I get on genshin LMAO I don't care to show off what I have if I did I would be like yaekith going around flexing my exploits to everyone in my way. And this has nothing to do with the fact of the matter here anyways even if what you said was true. Stop reaching Kirai.
6 I'm just waiting for your direct contradiction to what he claimed, he's showed pretty sufficient evidence already so I think it's your turn. 
7. And you did not all you did was feign some alibi about how he started the call asking you for stuff or whatever and some nebulous github commit with no date and time of when you committed it that's not enough to prove anything.

**Comment by ImStellar** [comment]
Ah our discussions always get cut-short you can't ever finish a conflict civilly

**Comment by ImStellar** [comment]
I think you over-estimate my patience Kirai chan

**Comment by ImStellar** [comment]
I mean I'm willing to Segway this argument into something else entirely different, what exactly makes skidding necessarily a bad thing? My beliefs are just different from yours I believe that copyright belongs to no one and that if someone made something of yours that's better then they have full right to profit off of it or use it, in the end what this does is makes more competition for better products and it also prevents monopolies. For example the pharmaceutical industry has massive monopolies on things like insulin all could of been avoided if things like patents, trademarks, copyright wasn't an issue that would mean that the price for insulin would go drastically down and be able to be produced much more that's just one example of how this demolishment of monopolies is better for the people. The whole stigma behind "skidding" is just coders mad someone used something they made and did it better than they did or with less effort. This is just my ideology again I'm not really hurting anyone using someone else's extensions. This mod is useful for the people of this game. I even gave love credit for the extensions part.

**Comment by ImStellar** [comment]
![image](https://user-images.githubusercontent.com/82069239/124222454-a578ea00-dab6-11eb-99ec-824134b7cef5.png)
oh would you look at that kirai chan requi also uses other people's code someone you implied was a SuPreMe CoDEr

**Comment by ImStellar** [comment]
Technically requi is a skid then. Again I'm not the one making the skidding thing a problem YOU ARE, it's honestly such flawed logic and an overused insult that means nothing.

**Comment by ImStellar** [comment]
![image](https://user-images.githubusercontent.com/82069239/124222779-44054b00-dab7-11eb-8bc6-3b0e5d353755.png)
oh what do you know the person you cherrypicked also believes skidding isn't inherently bad? Wow! Again what did I do wrong here in your eyes again?

**Comment by xKiraiChan** [comment]
Calm down, I said I was busy writing code. 
Leave you echo chamber already. It has been 20 minutes and you are still going on.

> I think you overestimate my patience Kirai chan

kinda cringe ngl

You are having and argument consisting of nobody but yourself. You are making points from what you *think* I would say and not what I have actually said.
Take a 1 hour break, re-read everything that I've said, and then come back and say something informed.

**Comment by ImStellar** [comment]
BTW love doesn't even have a license for any of his code I technically didn't even have to credit shit

**Comment by ImStellar** [comment]
> Calm down, I said I was busy writing code.
> Leave you echo chamber already. It has been 20 minutes and you are still going on.
> 
> > I think you overestimate my patience Kirai chan
> 
> kinda cringe ngl
> 
> You are having and argument consisting of nobody but yourself. You are making points from what you _think_ I would say and not what I have actually said.
> Take a 1 hour break, re-read everything that I've said, and then come back and say something informed.

HAHAHAHAH THIS WAS SO CHILDISH

**Comment by ImStellar** [comment]
> Calm down, I said I was busy writing code.
> Leave you echo chamber already. It has been 20 minutes and you are still going on.
> 
> > I think you overestimate my patience Kirai chan
> 
> kinda cringe ngl
> 
> You are having and argument consisting of nobody but yourself. You are making points from what you _think_ I would say and not what I have actually said.
> Take a 1 hour break, re-read everything that I've said, and then come back and say something informed.

Hold your L kirai chan. See what happens when you don't have 5 people screaming at me while arguing with me? Gets kinda hard huh?

**Comment by ImStellar** [comment]
See what you do is you insert your random 2 cents onto my twitter, discord server, or github and just dip. Just like Love!!! This is why I delete your thread since you clearly don't ever want to have a one on one debate with me I'm just not gonna let your sporadic half-wit assertions prolong on my profile.

**Comment by ImStellar** [comment]
This isn't an echo chamber you are still here. You can respond you just choose not to.

**Comment by ImStellar** [comment]
Well that's actually sad kirai chan I hoped we could of settled this conflict once and for all and we could of been friends I mean at our first encounter in love's call you seemed pretty chill just a little off-setting with your laugh, but it turns out you are just another egotistical coder who got angry over a misconception and refuses the acknowledge the reality of the situation he was wrong in.  Closing this thread soon...
